let cartas = [
    {
        value: 1,
        img: "../img/mago.jpeg",
        nombre: "El Mago",
        txt: "Se asocia con el pluricosmos, con la fractura de la superfuerza inicial. El mago es un hombre, se halla de frente con los pies firmemente asentados en el suelo y con la cabeza inclinada hacia la izquierda, lo que sugiere una acción directa predicha de suficiente reflexión." ,
    },
    {
        value: 2,
        img: "../img/sacerdotisa.jpeg",
        nombre: "La Suma Sacerdotisa",
        txt: "Se asocia con el cosmos, como pareja de dos universos gemelos, y con la carga eléctrica. Ella se encuentra en la antesala del Templo, que a un lado tiene una columna blanca y al otro lado negra.",
    },
    {
        value: 3,
        img: "../img/emperatriz.jpeg",
        nombre: "La Emperatriz",
        txt: "Se asocia con la Vía Láctea, representada por el manantial que discurre cerca, con la gravedad física representada por el avanzado estado de gestación que la conmueve y con el proceso de estructuración representado por su cetro.",
    },
    {
        value: 4,
        img: "../img/emperador.jpeg",
        nombre: "El Emperador ",
        txt: "El número del Emperador es el Cuatro, que según el tarot, representa la solidez: el cuatro es generalmente asociado con un ciclo entero y completo, y de hecho, un ciclo se concreta desde El Mago hasta El Emperador.",
    },
    {
        value: 5,
        img: "../img/sacerdote.jpeg",
        nombre: "El Sumo Sacerdote ",
        txt: "Es el mediador entre lo mundano y lo divino. Es un puente entre la iluminación interna y la vida externa. Representa todas las estructuras que defienden sistemas de creencias. El número 5 de esta carta simboliza la humanidad.",
    },
    {
        value: 6,
        img: "../img/enamorados.jpeg",
        nombre: "Los enamorados",
        txt: "Generalmente representa la elección de un camino en lugar de otro, la encrucijada que requiere una decisión radical ya que cualquier rumbo tomado implicará dejar otra oportunidad atrás, como sería escoger a una pareja sobre otra.",
    },
    {
        value: 7,
        img: "../img/carro.jpeg",
        nombre: "El Carro",
        txt: "El Carro representa el control de la mente humana sobre las pasiones animales y el instinto, o más esotéricamente, el Yo Superior sobre los bajos egos y agregados psicológicos.",
    },
    {
        value: 8,
        img: "../img/justicia.jpeg",
        nombre: "La Justicia",
        txt: "Su significado difiere dependiendo de su posición: de forma normal, significa el sostén de la fuerza moral e integridad. De forma inversa significa el perjuicio, intolerancia, falsos testimonios, etc",
    },
    {
        value: 9,
        img: "../img/ermitaño.jpeg",
        nombre: "El Ermitaño",
        txt: "Según el tarot, el Ermitaño representa la introspección, la meditación en solitario, la necesidad de autoconocimiento, de retiro del mundo para entender mejor lo aprendido y asimilarlo.",
    },
    {
        value: 10,
        img: "../img/rueda.jpeg",
        nombre: "La Rueda de la Fortuna",
        txt: "La Rueda de la Fortuna generalmente representa el vaivén de la vida, el Destino y el Karma. En el Tarot Mítico, por ejemplo, es representada por las Moiras.",
    },
    {
        value: 11,
        img: "../img/fuerza.jpeg",
        nombre: "La Fuerza",
        txt: "Según el tarot, usualmente simboliza que la voluntad que se antepone a cualquier problema, para encauzarlo y solucionarlo.",
    },
    {
        value: 12,
        img: "../img/colgado.jpeg",
        nombre: "El Colgado",
        txt: "El Colgado suele ser asociado con el autosacrificio y la paciencia ante las adversidades. Con el esfuerzo tesonero que requiere cualquier empresa difícil de llevar a cabo y cualquier causa noble.",
    },
    {
        value: 13,
        img: "../img/muerte.jpeg",
        nombre: "La Muerte",
        txt: "La carta de la Muerte no representa literalmente la muerte física y no necesariamente es un vaticinio negativo. La Muerte presenta el cambio, el fin de un ciclo y el resurgimiento de otro.",
    },
    {
        value: 14,
        img: "../img/templanza.jpeg",
        nombre: "La Templanza",
        txt: "A diferencia de otros seres que aparecen en la baraja del tarot, que son de corte espiritual, ella sí toca el suelo, pero con un pie morado, color poco frecuente en las imágenes que simboliza la máxima santidad.",
    },
    {
        value: 15,
        img: "../img/diablo.jpeg",
        nombre: "El Diablo",
        txt: "Generalmente el tarot considera que el Diablo representa al ser humano que está atado a los deseos materiales, los vicios y la materia. Suele representar el materialismo, la lujuria, la degradación y los excesos.",
    },
    {
        value: 16,
        img: "../img/torre.jpeg",
        nombre: "La Torre",
        txt: "La Torre representa la ira divina con el rayo destrozando lo construido y se interpreta que vaticina desastres y ruina. La Torre de Babel que es destruida por tener cimientos débiles.",
    },
    {
        value: 17,
        img: "../img/estrella.jpeg",
        nombre: "La Estrella",
        txt: "Todo en esta carta evoca a la paz interior y exterior, la espiritualidad, y armonía: azules aguas, una hermosa y pura joven, un cielo estrellado y un pájaro negro dispuesto para llevarse consigo cualquier negatividad existente.",
    },
    {
        value: 18,
        img: "../img/luna.jpeg",
        nombre: "La Luna",
        txt: "La carta representa la vida de la imaginación apartada de la vida del espíritu, el perro y el lobo son los miedos naturales de la mente en presencia de ese lugar de salida, cuando hay sólo luz reflejada como luz intelectual.",
    },
    {
        value: 19,
        img: "../img/sol.jpeg",
        nombre: "El Sol",
        txt: "Se dice que  esta carta refleja felicidad y satisfacción, vitalidad, autoconfianza y éxito. A veces conocida como la mejor carta del Tarot, representa cosas buenas y resultados positivos para las luchas actuales.",
    },
    {
        value: 20,
        img: "../img/juicio.jpeg",
        nombre: "El Juicio",
        txt: "Siempre revela una transformación, como un cambio total de vida, de actitud e incluso a veces de personalidad, en vistas a una liberación de la etapa anterior.",
    },
    {
        value: 21,
        img: "../img/mundo.jpeg",
        nombre: "El Mundo",
        txt: "Es una referencia englobadora del conocimiento de la Biblia, según el cristianismo, la palabra de Dios.",
    },
];


